### ISSUE TITLE
Question: Bundle files

### ISSUE THREAD

**Issue by ruswerner** [esp-rs/esp-storage#11]
I'm somewhat new to Rust and very new to ESP on Rust. I am struggling to find information on how to embed and then use file resources on ESP via Rust. I am primarily interested in flashing a directory tree of HTML templates to serve via the HTTP server. I have been embedding these assets in the binary using this:

https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-guides/build-system.html#embedding-binary-data

Is there an equivalent to this for ESP on Rust? Is there a better approach I should follow? I can't seem to find any information or examples in the various books, awesome lists, GH issues, etc.

Cheers

**Comment by bjoernQ** [comment]
For single files `include_bytes!` or `include_str!` should work - for multiple fiels you probably need some external crate.

A quick look at crates.io reveals a lot of those macros but it's not clear if and which of them work for no-std
