### ISSUE TITLE
flash address 

### ISSUE THREAD

**Issue by oleid** [esp-rs/esp-storage#15]
The demo hard codes `let flash_addr = 0x9000;`.
I'm wondering if this address always works or how I can find a valid address. 

While writing this issue I found https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html which states that the default partition table is at `0x8000` and is `0x1000` long. That would fit the aforementioned flash address nicely.
So maybe just a comment in the example is missing. What do you think?

**Comment by bjoernQ** [comment]
In the default partition table 0x9000 is NVS (`nvs,      data, nvs,     0x9000,  0x6000,`) so it's fine to use it

Probably worth to mention that in a comment about it in the example

**Comment by katyo** [comment]
@oleid You can use [esp-partition-table](https://crates.io/crates/esp-partition-table) crate to find desired partition address and length.

**Comment by bjoernQ** [comment]
This crate moves to the esp-hal repo. Will be done there
