### ISSUE TITLE
Reading external USB stick (mass storage)

### ISSUE THREAD

**Issue by porteux** [esp-rs/esp-storage#18]
Is it possible to adapt/extend the code of this project to read an external USB stick plugged into the USB HOST port of a ESP32-S3?

Thanks!

**Comment by bjoernQ** [comment]
This is a library crate for bare-metal only and currently there is no support for USB HOST yet in bare-metal.
Most probably once we get support for it this won't be the place where we would add such a feature.

**Comment by porteux** [comment]
I see. Thanks! :)
