### ISSUE TITLE
Firmware updates from Rust

### ISSUE THREAD

**Issue by mangelajo** [esp-rs/esp-storage#2]
Hey,

  Are there any examples to perform firmware updates from rust?

Thanks!

**Comment by bjoernQ** [comment]
Yes, there is an example for ESP32-C3: https://github.com/bjoernQ/esp32c3-ota-experiment

**Comment by bjoernQ** [comment]
I guess we can close this since the example is linked in https://github.com/esp-rs/awesome-esp-rust and should be portable to other ESP targets
