### ISSUE TITLE
esp32 write seems to only work for the first 32 bytes of a sector

### ISSUE THREAD

**Issue by karlri** [esp-rs/esp-storage#22]
On esp32, if reading and writing 32 bytes at the start of a flash sector, it works as expected.

If on the other hand you attempt to write byte index 33 of a sector, there seems to be some kind of problem. When reading the data back, you don't get the data that was written.

Tested with 
```
[profile.release]
opt-level = 3
lto = false
```

**Comment by bjoernQ** [comment]
I can reproduce this and can confirm this is a bug

**Comment by bjoernQ** [comment]
There is a fix for this in #23 
Would be great if you could check it actually fixes your problem. 
With that I was able to successfully perform an OTA update on ESP32

**Comment by karlri** [comment]
Sweet, my flashing code now runs without issues :) Thanks for the quick fix! The fix also totally makes sense.
