### ISSUE TITLE
ESP32 flash capacity is always reported as 0

### ISSUE THREAD

**Issue by jobafr** [esp-rs/esp-storage#35]
Hi, I'm using an ESP32 with 4MB of memory, and
```rust
    let mut flash = FlashStorage::new();
    log::error!("flash capacity {:?}", flash.capacity());
```
reports "flash capacity 0".

This is my partitions.csv:
```csv
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x4000,
otadata,  data, ota,     0xd000,  0x2000,
phy_init, data, phy,     0xf000,  0x1000,
ota_0,    app,  ota_0,   0x10000, 0x180000,
ota_1,    app,  ota_1,   0x190000, 0x180000,
```

I'm using the latest git from this repo (`869f6c8c258bfe579b64f856bbbb38c9b8a381d1`), `features = ["esp32", "low-level"]`, and `cargo espflash flash --flash-size=4mb` (though the latter does not seem to make a difference).

I looked into the code that tries to determine the capacity, and when I dump the memory region it reads, I get this:
```
$ esptool.py --port /dev/ttyACM0 read_flash 0x1000 0x08 capacity.bin
esptool.py v4.6.2
Serial port /dev/ttyACM0
Connecting.......
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: [censored for github]
Uploading stub...
Running stub...
Stub running...
8 (100 %)
8 (100 %)
Read 8 bytes at 0x00001000 in 0.0 seconds (7.2 kbit/s)...
Hard resetting via RTS pin...
$ hexdump capacity.bin
0000000 04e9 2002 064c 4008                    
0000008
```

Please let me know if I can provide additional debug info.

**Comment by bjoernQ** [comment]
Looks like reading flash isn't working since `0x20` would indicate 4 MB

Does the demo in this repository work for you?

**Comment by jobafr** [comment]
Hi, thanks, the demos seem to work as intended (both the normal one and the low-level one). In my application, I'm using this crate as well as [esp-ota](https://crates.io/crates/esp-ota), with the partition layout recommended in their readme. The intention is to use esp-ota for remote updating (this works already) and to use esp-storage to persist some info (serial number, settings, etc.) on the device. Could there be some interaction between these two crates that I need to be aware of?

Is the partition table format (or whatever it is that esp-storage is reading at 0x1000) documented somewhere?

**Comment by bjoernQ** [comment]
I guess your project is using `std`? This crate for use on bare-metal (`no_std`)

We usually use the prefix `esp-idf-` for crates which target `std` on top of esp-idf and just `esp-` for crates which target `no_std`/bare-metal. Unfortunately 3rd party crates don't seem to adopt this naming scheme

**Comment by jobafr** [comment]
Ah yes, I'm using the esp-idf- stuff. I looked around and it seems [the nvs module in esp-idf-svc](https://esp-rs.github.io/esp-idf-svc/esp_idf_svc/nvs/struct.EspNvsPartition.html) is what I need to use?

**Comment by bjoernQ** [comment]
> Ah yes, I'm using the esp-idf- stuff. I looked around and it seems [the nvs module in esp-idf-svc](https://esp-rs.github.io/esp-idf-svc/esp_idf_svc/nvs/struct.EspNvsPartition.html) is what I need to use?

I think yes - that's probably what you need

**Comment by jobafr** [comment]
Thank you very much, works perfectly!

**Comment by bjoernQ** [comment]
Great to hear it's working for you
