### ISSUE TITLE
Soundness issue: `FlashSectorBuffer.data` alignment

### ISSUE THREAD

**Issue by wetheredge** [esp-rs/esp-storage#37]
`FlashSectorBuffer` definition: https://github.com/esp-rs/esp-storage/blob/869f6c8c258bfe579b64f856bbbb38c9b8a381d1/src/common.rs#L4-L7

My understanding of the `#[repr(align(x))]` attribute is that it only affects the alignment of the structure, not the fields or padding within it. Additionally, [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c7318167948ccba929b73da01eadc40) shows the `data` field has a minimum alignment of 1, not 4.
* https://doc.rust-lang.org/reference/type-layout.html#the-alignment-modifiers
* https://doc.rust-lang.org/reference/type-layout.html#the-rust-representation

My thought is to give `data` the type `[u32; SECTOR_SIZE / 4]` and remove the `#[repr(align(4))]` attribute. The byte array can be accessed using `bytemuck`:
```rust
impl Deref for FlashSectorBuffer {
    type Target = [u8; FlashStorage::SECTOR_SIZE as usize];

    fn deref(&self) -> &Self::Target {
        bytemuck::cast_ref(&self.data)
    }
}

impl DerefMut for FlashSectorBuffer {
    fn deref_mut(&mut self) -> &mut Self::Target {
        bytemuck::cast_mut(&mut self.data)
    }
}
```

If all this looks right, I'm happy to open a PR with the fix.

**Comment by bjoernQ** [comment]
Thanks! Another option might be to add a field like `_alignment: [u32; 0]` to the struct

**Comment by MabezDev** [comment]
Good spot! Thank you for looking into this, this is definitely a omission by me when I implemented this. I think the simplest solution would be adding `repr(C, align(4))`. This should give a stable, unchanging layout with the correct alignment. Would you mind PRing that?

**Comment by wetheredge** [comment]
> add a field like `_alignment: [u32; 0]` to the struct

Afaik this is identical to `#[repr(align(4))]`.

> `repr(C, align(4))`

Adding this to the playground link still says `data` is unaligned, but based on [the docs for `repr(C)`](https://doc.rust-lang.org/reference/type-layout.html#reprc-structs), looks like it should be aligned so long as no fields are added before it.

I still think using `[u32; SECTOR_SIZE / 4]` (with `bytemuck` to convert to `[u8; SECTOR_SIZE]`) is clearer and better models the hardware. It's what I'm using in my own code. Is there a particular reason you dislike this solution? A plain [`transmute()`](https://doc.rust-lang.org/core/mem/fn.transmute.html) of the reference would also work, but from what I can tell (see <https://godbolt.org/z/j4cbx3rs6>), `bytemuck::cast_ref` gets optimized away on any opt-level other than 0.

**Comment by bjoernQ** [comment]
I'm not against `bytemuck` especially since it doesn't pull in a lot of transitive dependencies. While I haven't checked myself, I would expect it to be of the same cost as `transmute()`. IIRC also esp-hal uses the `/4` / `*4` "pattern" in a few places

**Comment by MabezDev** [comment]
> Adding this to the playground link still says data is unaligned, but based on [the docs for repr(C)](https://doc.rust-lang.org/reference/type-layout.html#reprc-structs), looks like it should be aligned so long as no fields are added before it.

Yeah, this is why I suggested it, its the simplest _and_ we know it will never change in the future. I still think this is the best approach. If you wish, you could add a comment about never adding new fields to ensure proper alignment of the inner buffer?
